version: '3'

networks:
    bibbox-default-network:
      external: true

services:
  bibbox-galaxy-server:
    image: galaxy/galaxy-anvil:23.0
    container_name:  bibbox-galaxy-server
    restart: unless-stopped
    networks:
      - bibbox-default-network
    hostname: bibbox-galaxy-server
    privileged: True
    ports:
      - 8080:8080
    volumes: 
      - ./data/database:/galaxy/server/database


