version: '3'

networks:
    bibbox-default-network:
      external: true

services:
  bibbox-galaxy-server:
    image: quay.io/bgruening/galaxy-server:20.09
    container_name:  bibbox-galaxy-server
    restart: unless-stopped
    networks:
      - bibbox-default-network
    hostname: bibbox-galaxy-server
    privileged: True
    ports:
      - 5555:5555
    volumes: 
      - ./data/export:/export/:delegated
      - ./data/export/munge:/etc/munge
      - ./data/export/slurm_config:/etc/slurm-llnl
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - bibbox-galaxy-postgres
      - bibbox-galaxy-rabbitmq
    links:
      - bibbox-galaxy-rabbitmq:rabbitmq
      - bibbox-galaxy-postgres:postgres
#    environment:
#      - GALAXY_DEFAULT_ADMIN_USER=admin
#      - GALAXY_DEFAULT_ADMIN_EMAIL=admin@galaxy.org
#      - GALAXY_DEFAULT_ADMIN_PASSWORD=password
#      - GALAXY_DEFAULT_ADMIN_KEY=fakekey
  # The database for Galaxy
  bibbox-galaxy-postgres:
    image: postgres:12
    container_name: bibbox-galaxy-postgres
    hostname: bibbox-galaxy-postgres
    environment:
      - POSTGRES_PASSWORD=chaopagoosaequuashie
      - POSTGRES_USER=galaxy
      - POSTGRES_DB=galaxy
    volumes:
      - ./data/export/postgres/:/var/lib/postgresql/data:delegated
    networks:
      - bibbox-default-network

# Message queue for better performance
  bibbox-galaxy-rabbitmq:
    image: rabbitmq:3.9.13-alpine
    container_name: bibbox-galaxy-rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=galaxy
      - RABBITMQ_DEFAULT_PASS=vaiJa3ieghai2ief0jao
      - RABBITMQ_DEFAULT_VHOST=galaxy
    volumes:
      - ./data/export/rabbitmq:/var/lib/rabbitmq:delegated
    networks:
      - bibbox-default-network
      
  # The galaxy-configurator is responsible for the whole configuration of
  # your setup and should be the central place of configuration.
  bibbox-galaxy-configurator:
    image: quay.io/bgruening/galaxy-configurator:20.09
    #build: galaxy-configurator
    container_name: bibbox-galaxy-configurator
    environment:
      - EXPORT_DIR=./data/export
      - HOST_PWD=$PWD
      - GALAXY_OVERWRITE_CONFIG=true
      - GALAXY_DEPENDENCY_RESOLUTION=conda
      - GALAXY_JOB_RUNNER=local
      - GALAXY_CONFIG_ADMIN_USERS=admin@bibbox.org
      - GALAXY_CONFIG_DATABASE_CONNECTION=postgresql://galaxy:chaopagoosaequuashie@postgres/galaxy
      - GALAXY_CONFIG_GALAXY_INFRASTRUCTURE_URL=${GALAXY_CONFIG_GALAXY_INFRASTRUCTURE_URL:-http://localhost}
      - GALAXY_CONFIG_CONDA_AUTO_INSTALL=true
#      - GALAXY_CONFIG_AMQP_INTERNAL_CONNECTION=amqp://galaxy:vaiJa3ieghai2ief0jao@rabbitmq/galaxy
      - GALAXY_PROXY_PREFIX=${GALAXY_PROXY_PREFIX:-}
      - GALAXY_CONFIG_CLEANUP_JOB=onsuccess
      - NGINX_OVERWRITE_CONFIG=true

#      - GALAXY_JOB_RUNNER=slurm
#      - SLURM_OVERWRITE_CONFIG=true
#      - SLURM_NODE_COUNT=${SLURM_NODE_COUNT:-1}
#      - SLURM_NODE_HOSTNAME=compose_slurm_node

    volumes:
      - ./data/export/galaxy/config:/galaxy/config
      - ./data/export/nginx:/etc/nginx
      - ./data/base_config.yml:/base_config.yml
      - ./data/galaxy-configurator/templates:/templates
    networks:
      - bibbox-default-network

  # The proxy server. All web-traffic is going through here, so we can
  # offload static file serving
  # (https://docs.galaxyproject.org/en/master/admin/production.html#using-a-proxy-server)
  bibbox-galaxy-nginx:
    image: quay.io/bgruening/galaxy-nginx:20.09
    #build: bibbox-galaxy-nginx
    container_name: bibbox-galaxy-nginx
    ports:
      - "8080:80"
    volumes:
      - ./data/export/nginx:/config:ro
      - ./data/export/galaxy/static:/export/galaxy/static:ro
      - ./data/export/galaxy/config/plugins:/galaxy/config/plugins:ro
    links:
      - bibbox-galaxy-server:galaxy-server
      - bibbox-galaxy-rabbitmq:rabbitmq
      - bibbox-galaxy-postgres:postgres
   
    depends_on:
      - bibbox-galaxy-server
    networks:
      - bibbox-default-network
#  slurmctld:
#    image: quay.io/bgruening/galaxy-slurm:20.09
#    #build: galaxy-slurm
#    container_name: bibbox-galaxy-slurmctld
#    command: ["slurmctld"]
#    hostname: slurmctld
#    volumes:
#      - ./data/export/slurm_config:/etc/slurm-llnl
#      - ./data/export/munge:/etc/munge
#    networks:
#      - bibbox-default-network
#  slurm_node_discovery:
#    image: quay.io/bgruening/galaxy-slurm-node-discovery:20.09
#    #build: galaxy-slurm-node-discovery
#    container_name: bibbox-galaxy-slurm-node-discovery
#    volumes:
#      - ./data/export/slurm_config:/etc/slurm-llnl
#      - /var/run/docker.sock:/var/run/docker.sock
#  slurm_node:
#    image: quay.io/bgruening/galaxy-slurm:20.09
#    #build: galaxy-slurm
#    #container_name: bibbox-galaxy-slurm-node
#    command: ["slurmd"]
#    privileged: true
#    labels:
#      slurm_node: true
#    volumes:
#      - ./data/export/galaxy/database:/galaxy/database
#      - ./data/export/galaxy/tools:/galaxy/tools:ro
#      - ./data/export/galaxy/lib/galaxy/tools:/galaxy/lib/galaxy/tools:ro
#      - ./data/export/galaxy/tool-data:/galaxy/tool-data
#      - ./data/export/galaxy/.venv:/galaxy/.venv
#      - ./data/export/tool_deps:/tool_deps
#      - ./data/export/slurm_config:/etc/slurm-llnl
#      - ./data/export/munge:/etc/munge
#      - /var/run/docker.sock:/var/run/docker.sock
#    networks:
#      - bibbox-default-network


#services:
#  bibbox-galaxy:
#    image: bgruening/galaxy-stable:20.09
#    container_name:  bibbox-galaxy
#    restart: unless-stopped
#    networks:
#      - bibbox-default-network
#    ports:
#      - "8080:80"
#      - "8021:21"
#      - "8022:22"
#    volumes: 
#      - ./data/export:/export/ 
#    environment:
#      - GALAXY_DEFAULT_ADMIN_USER=admin
#      - GALAXY_DEFAULT_ADMIN_EMAIL=admin@bibbox.org
#      - GALAXY_DEFAULT_ADMIN_PASSWORD=password
#      - GALAXY_DEFAULT_ADMIN_KEY=fakekey

